default_platform(:ios)

platform :ios do

    desc "Release a new version"
    lane :release do |options|
      target_version = options[:version]
      raise "The version is missed. Use `fastlane release version:{version_number}`.`" if target_version.nil?

      ensure_git_branch(branch: "(release/*)|(hotfix/*)")

      # TODO: Add cocoapods?
      # podspec = ENV["PODSPEC"]
      # version_bump_podspec(path: podspec, version_number: target_version)
      # git_add
      # git_commit(
      #     path: ["DynamicOverlay.podspec"],
      #     message: "Bump to #{target_version}"
      # )
      # ensure_git_status_clean

      add_git_tag(tag: target_version)

      changelog = read_changelog(
          changelog_path: "CHANGELOG.md",
          section_identifier: "[#{target_version}]"
      )

      # Push
      push_to_git_remote
      push_git_tags(tag: target_version)
      UI.success "Pushed 🎉"

      # TODO: Release cocoapods?
      # pod_push
      # UI.success "Released 🎉"

      # Release Github

      set_github_release(
          repository_name: "gaetanzanella/swift-ssh-client",
          api_token: ENV["GITHUB_TOKEN"],
          name: "v#{target_version}",
          tag_name: "#{target_version}",
          description: changelog,
      )

      # Make PR
      create_pull_request(
          api_token: ENV["GITHUB_TOKEN"],
          repo: "gaetanzanella/swift-ssh-client",
          title: "Release #{target_version}",
          base: "main",
          body: changelog
      )
    end
end